name: Main

on:
  push:
    branches:
      - main

env:
  NEXT_TELEMETRY_DISABLED: 1

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: ./.github/actions/pnpm-install

      - name: ESLint
        shell: bash
        run: pnpm lint

  typecheck:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: ./.github/actions/pnpm-install

      - name: Typecheck
        run: pnpm typecheck

  build:
    runs-on: ubuntu-latest

    needs:
      - lint
      - typecheck

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: ./.github/actions/pnpm-install

      - name: Next.js build & export
        run: pnpm run build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
          deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          publish_dir: ./out
          cname: tahri.dev
