name: PR

on:
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: /.github/pnpm-install@main

      - name: ESLint
        shell: bash
        run: pnpm lint

  typecheck:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: /.github/pnpm-install@main

      - name: Typecheck
        run: pnpm typecheck

  build:
    runs-on: ubuntu-latest

    needs:
      - lint
      - typecheck

    steps:
      - uses: actions/checkout@v3

      - uses: /.github/pnpm-install@main

      - name: Next.js build
        run: pnpm run build

  export:
    runs-on: ubuntu-latest

    needs: build

    steps:
      - uses: actions/checkout@v3

      - uses: /.github/pnpm-install@main

      - name: Export static files
        run: pnpm run export
