name: Deploy to Github Pages

on:
  push:
    branches:
      - main

jobs:
  build:
    uses: ./.github/workflows/reusable-build.yml
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          publish_dir: ./out
          cname: tahri.dev



